import { StyleSheet } from 'react-native';
import { colors, spacing, radius, shadows } from '@/core/theme';

export const styles = StyleSheet.create({
    container: {
        paddingHorizontal: 20,
        paddingTop: 24,
        paddingBottom: 40,
        backgroundColor: '#F8F9FC',
    },
    listContainer: {
        paddingHorizontal: 20,
        paddingBottom: 24,
        backgroundColor: '#F8F9FC', // Fondo gris claro idéntico a la imagen
        flexGrow: 1,
    },
    menuContainer: {
        gap: 16,
        marginBottom: 32,
    },
    headerContainer: {
        marginTop: 24,
        // marginBottom: 20,
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 14,
    },
    mainTitle: {
        fontSize: 26,
        fontWeight: 'bold',
        color: '#1C2434',
        marginBottom: 6,
    },
    mainSubtitle: {
        fontSize: 14,
        color: '#64748B',
        marginBottom: 16
    },
    card: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 16, // Bordes muy suaves
        padding: 20,
        marginBottom: 16,
        // Configuración de sombras nativas para iOS y Android
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
        elevation: 2,
    },
    iconBox: {
        width: 48,
        height: 48,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    iconContainer: {
        width: 56,
        height: 56,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    textContainer: {
        marginLeft: 16,
        flex: 1,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1C2434',
        marginBottom: 4,
    },
    cardSub: {
        fontSize: 12,
        color: '#64748B',
        marginTop: 2,
    },
    adminActionContainer: {
        gap: 12,
        marginTop: 8,
    },
    btn: {
        flexDirection: 'row',
        height: 48,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
    },
    btnGreen: {
        backgroundColor: '#00BA52',
    },
    btnBlue: {
        backgroundColor: '#2F70F2',
    },
    btnText: {
        color: '#FFFFFF',
        fontSize: 15,
        fontWeight: '600',
    },
    cardSubtitle: {
        fontSize: 13,
        color: '#64748B',
    },
    backButtonText: {
        color: '#64748B', // Usa tu paleta de colores del tema global si existe
        fontSize: 15,
        fontWeight: '600',
    },
    backButtonContainer: {
        width: '100%',
        alignItems: 'flex-start',
        marginBottom: 12,
        paddingHorizontal: 4, // Pequeño margen para que no pegue directo al borde de la pantalla
    },
    // Área táctil del botón volver (facilita la pulsación del usuario)
    backButton: {
        paddingVertical: 8,
        paddingRight: 16, // Espacio interactivo hacia la derecha
    },
    customCardTitle: {
        fontSize: 16,
        fontWeight: '500',
        color: '#1C2434',
        marginBottom: 4,
    },
    yearTextBold: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1C2434',
    },
    toggleCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginBottom: 24,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.03,
        shadowRadius: 6,
        elevation: 2,
    },
    toggleHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 6,
    },
    toggleTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1C2434',
        flex: 1,
    },
    toggleSubtitle: {
        fontSize: 12,
        color: '#64748B',
        lineHeight: 16,
        paddingLeft: 28,
    },
    // ESTILOS PARA REALIZACIÓN DE TEST
    headerControlContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderColor: '#E2E8F0',
    },
    examSubtitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#64748B',
    },
    finishHeaderButton: {
        backgroundColor: '#FEE2E2',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#FCA5A5',
    },
    finishHeaderButtonText: {
        color: '#DC2626',
        fontWeight: '700',
        fontSize: 13,
    },
    statusCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        flexDirection: 'row',
        alignItems: 'center',
    },
    progressTextContainer: {
        flexDirection: 'row',
        alignItems: 'baseline',
    },
    progressTitle: {
        fontSize: 13,
        color: '#64748B',
    },
    progressTotal: {
        fontSize: 13,
        fontWeight: 'bold',
        color: '#1E293B',
    },
    progressBarBackground: {
        flex: 1,
        height: 6,
        backgroundColor: '#F1F5F9',
        borderRadius: 3,
        marginHorizontal: 12,
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: '#2563EB', // Color primario de tu tema
        borderRadius: 3,
    },
    timerBadge: {
        backgroundColor: '#F8FAFC',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    timerText: {
        fontSize: 13,
        fontWeight: '700',
        color: '#334155',
    },
    questionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        marginBottom: 20,
    },
    questionText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0F172A',
        lineHeight: 24,
        marginBottom: 20,
    },
    optionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 12,
        padding: 14,
        marginBottom: 12,
        backgroundColor: '#FFFFFF',
    },
    optionCardSelected: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#2563EB',
        borderRadius: 12,
        padding: 13,
        marginBottom: 12,
        backgroundColor: '#EFF6FF',
    },
    optionCardCorrect: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#10B981',
        borderRadius: 12,
        padding: 13,
        marginBottom: 12,
        backgroundColor: '#ECFDF5',
    },
    optionCardIncorrect: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#EF4444',
        borderRadius: 12,
        padding: 13,
        marginBottom: 12,
        backgroundColor: '#FEF2F2',
    },
    optionCircle: {
        width: 32,
        height: 32,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#CBD5E1',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    optionCircleSelected: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#2563EB',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    optionCircleCorrect: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#10B981',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    optionCircleIncorrect: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#EF4444',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    optionText: {
        fontSize: 14,
        color: '#475569',
        fontWeight: '600',
    },
    optionTextSelected: {
        fontSize: 14,
        color: '#FFFFFF',
        fontWeight: '700',
    },
    optionLabel: {
        fontSize: 15,
        color: '#334155',
        flex: 1,
    },
    explanationCard: {
        backgroundColor: '#F0F9FF',
        borderRadius: 12,
        padding: 14,
        marginTop: 8,
        borderWidth: 1,
        borderColor: '#BAE6FD',
    },
    explanationHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    explanationTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#0369A1',
    },
    explanationText: {
        fontSize: 13,
        color: '#0C4A6E',
        lineHeight: 18,
    },
    actionsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
        marginBottom: 20,
    },
    primaryButton: {
        flex: 1,
        backgroundColor: '#2563EB',
        borderRadius: 12,
        paddingVertical: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    primaryButtonDisabled: {
        flex: 1,
        backgroundColor: '#CBD5E1',
        borderRadius: 12,
        paddingVertical: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    primaryButtonText: {
        color: '#FFFFFF',
        fontWeight: '700',
        fontSize: 15,
    },
    secondaryButton: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        paddingVertical: 14,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#CBD5E1',
    },
    secondaryButtonText: {
        color: '#475569',
        fontWeight: '600',
        fontSize: 15,
    },
    scrollContainer: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 32, // Margen extra abajo para que los botones de acción no se peguen al borde físico de la pantalla
        backgroundColor: '#F8FAFC', // Fondo grisáceo claro muy limpio para que resalten las tarjetas blancas
    },
    /// EXAMSUMARYSCREEN
    mainTitleSumary: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1C2434',
    },
    scoreCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 20,
        alignItems: 'center',
        marginBottom: 20,
        elevation: 2,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
    },
    badgeContainer: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#EFF6FF',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    scoreNumber: {
        fontSize: 34,
        fontWeight: 'bold',
        color: '#1C2434',
    },
    scoreLabel: {
        fontSize: 13,
        color: '#64748B',
        fontWeight: '500',
    },
    gridContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    metricBox: {
        backgroundColor: '#FFFFFF',
        width: '48%',
        borderRadius: 12,
        padding: 14,
        marginBottom: 12,
        alignItems: 'center',
        elevation: 2,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.02,
        shadowRadius: 4,
    },
    metricValue: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#1C2434',
        marginTop: 4,
    },
    metricLabel: {
        fontSize: 11,
        color: '#64748B',
        marginTop: 2,
        textAlign: 'center',
        fontWeight: '500',
    },
    footerContainer: {
        marginTop: 12,
    },

    legendContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 8,
        marginTop: 8,
    },
    legendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    legendDot: {
        width: 12,
        height: 12,
        borderRadius: 6,
    },
    legendText: {
        fontSize: 12,
        color: '#64748B',
        fontWeight: '500',
    },
    backButtonContainerSumary: {
        width: '100%',
        marginBottom: 12,
    },
    backButtonSumary: {
        borderRadius: 10,
        paddingVertical: 12,
    },
    backButtonTextSumary: {
        fontSize: 15,
        fontWeight: '600',
    },
});